---
title: "LSTAT2120 - Linear Project"
author: "Lamy Lionel, Aurèle Bartolomeo, Rémi Gengler"
date: "26/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warnings = FALSE)
knitr::opts_chunk$set(eval = TRUE)
```

```{r}
opt.digits = 3
opt.barcolor = "#000033"
```


## Data importation and cleaning

```{r}

original = read.csv("./sources/foot_last.csv", sep=";", encoding = "utf8", skipNul = T, stringsAsFactors = F)
original = na.omit(original)

# Dummies variables
dummies = data.frame(model.matrix(~ Nationality - 1, data=original), 
                     model.matrix(~ Preferred_Foot - 1, data=original))

# Transformations
dataset = within(original, {

  Age = cut(Age, breaks=c(min(Age), round(kmeans(Age, centers = 3, nstart = 10)$centers), max(Age)+1), right=F)
    
  Weight  = round(as.numeric(Weight*0.453592))
  Height = round(sapply(Height, function(x) 
    as.numeric(strsplit(x, "'")[[1]][1])*12 + as.numeric(strsplit(x, "'")[[1]][2])*2.54))
  
  Value = Value_M * 10^6
  Wage = Wage_K * 1000
  
  Value_M = NULL
  Wage_K = NULL
  Nationality = NULL
  Preferred_Foot = NULL
})

# Splitting into training and validation
tmp = sample(nrow(dataset), round(.80*nrow(dataset)), replace=F)

train = dataset[tmp,]
valid = dataset[-tmp,]

rm(tmp)
```

## Descriptive analysis

```{r}
# Histogram of qualitative variable

par(mfrow=c(1,2))
barplot(prop.table(table(original$Nationality)), main="Nationality of the player", col = opt.barcolor, ylab="Percentage")
barplot(prop.table(table(original$Preferred_Foot)), main="Preferred foot of the player", col = opt.barcolor, ylab="Percentage")


# Mean, Sd, Skewness, Kurtosis
library(moments)
library(formattable) # Better print
library(ggplot2)

desc.quantitative = (function(data){
  
  addStats = function(col, name){
    
    return(data.frame(
      Variable=name,
      Mean = round(mean(col, na.rm = T), opt.digits),
      Std.Deviation = round(sd(col), opt.digits),
      Skewness = round(skewness(col), opt.digits),
      Kurtosis = round(kurtosis(col), opt.digits)
      ))
  }
  
  for (c in colnames(data)){
    if (exists("results")){
      results = rbind(results, addStats(data[[c]], c))
    }else{
      results = addStats(data[[c]], c)
    }
  }
  return (results)
   
})(dataset[0:-1])

desc.quantitative = desc.quantitative[order(as.character(desc.quantitative$Variable)),]
row.names(desc.quantitative) = NULL # hide row number

formattable(desc.quantitative,
            align=c("l", rep("c", ncol(desc.quantitative)-1)),
            list(Skewness = formatter("span", style = x ~ style(color= ifelse(abs(x) > 0.5, ifelse(abs(x) >= 2,"red", "orange"), "black")))))

# Boxplot and Histogram

desc.quantitative.boxplots = (function(data){
  
  drawBoxplot = function(co, name){
    par(cex=0.9, mai=c(0.1,0.1,0.2,0.1))
    
    par(fig=c(0.1, 1, 0.15, 0.95))
    # Tried a vertical hist but that's not pretty without ggplot
    hist(co, axes=T, main=paste0("Distribution de ", name), col = opt.barcolor, xlab="", xaxt="n")
    
    par(fig=c(0.1, 1, 0.05, 0.2), new=T)
    boxplot(co, horizontal = T)
  }
  
  sapply(colnames(data), function (x) drawBoxplot(data[[x]], x))
  
})(dataset[0:-1])

```


